# Generated by Django 4.0 on 2022-11-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GDSC_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='media/gallery/')),
                ('caption', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
